# Pytorch Basics - Tensors



Dear students, let me introduce this basic test that should assess your knowledge and experience in working with Pytorch and numpy-like tensors. If it is the first time when you hear about Pytorch you should not be frightened. Before each problem set, I will give some short examples of how Pytorch works and it should be enough for solving these problems. But if you need more information and examples you can find additional materials in [Pytorch Tutorials](https://pytorch.org/tutorials/), especially you can consider these links:


*   [Learn the Basics](https://pytorch.org/tutorials/beginner/basics/intro.html)
*   [Learning Pytorch with Examples](https://pytorch.org/tutorials/beginner/pytorch_with_examples.html)
*   [Tensors](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)



## Tensors

In [262]:
# Importing essential libraries
import numpy as np
import torch

## 1. Initializing a Tensor

In [263]:
# By Python list
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [264]:
# By numpy array
x_numpy = np.array([[4, 5, 6], [1, 2, 3]])
x = torch.from_numpy(x_numpy)
print(x)

tensor([[4, 5, 6],
        [1, 2, 3]])


In [265]:
# You can specify the type of data
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float)
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [266]:
# Important attributes of tensor
print("Shape of tensor:\n", x.shape)
print("Datatype of tensor:\n", x.dtype)

Shape of tensor:
 torch.Size([2, 3])
Datatype of tensor:
 torch.float32


In [267]:
# You can create basic tensors directly
shape = (2,3,)
ones = torch.ones(shape)
zeros = torch.zeros(shape)
rands = torch.rand(shape)
print("ones:\n", ones)
print("zeros:\n", zeros)
print("random numbers:\n", rands)

ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
random numbers:
 tensor([[0.7050, 0.3638, 0.2942],
        [0.9267, 0.7532, 0.2771]])


In [268]:
# Instead of specifying the shape directly you can specify it by a tensor's shape.
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float)
ones = torch.ones_like(x)
zeros = torch.zeros_like(x)
rands = torch.rand_like(x)
print("ones:\n", ones)
print("zeros:\n", zeros)
print("random numbers:\n", rands)

ones:
 tensor([[1., 1.],
        [1., 1.]])
zeros:
 tensor([[0., 0.],
        [0., 0.]])
random numbers:
 tensor([[0.2567, 0.7786],
        [0.9670, 0.6493]])


In [269]:
# You can initialize more interesting tensors
diagonal = torch.diag(torch.tensor([1, 2, 3]))
eye = torch.eye(3)
x_range = torch.arange(10)
print("diagonal matrix:\n", diagonal)
print("identity matrix:\n", eye)
print("range vector:\n", x_range)

diagonal matrix:
 tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])
identity matrix:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
range vector:
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### Function for validating solutions

In [270]:
# Your solutions will be validated using this function
def validate_solution(student_answer, correct_answer, test_num):
    x = student_answer
    y = correct_answer
    if y.shape == x.shape and torch.allclose(y, x, atol=1e-4):
        print(f"Test {test_num} passed!")
    else:
        raise AssertionError(f"Test {test_num} failed!")

### Problem 1.1

Write a function **diag_range_matrix** that takes $n$ and returns the diagonal matrix $\quad
\begin{pmatrix}
1 & 0 & \dots & 0 \\
0 & 2 & \dots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \dots & n
\end{pmatrix}
$ with type *float torch.Tensor*. 

In [271]:
def diag_range_matrix(n):
    return torch.diag(torch.arange(1, n + 1, dtype=torch.float))

In [272]:
# Test 1
output = diag_range_matrix(2)
correct = torch.tensor([[1, 0], [0, 2]], dtype=torch.float)
validate_solution(output, correct, test_num=1)


# Test 2
output = diag_range_matrix(5)
correct = torch.tensor(
    [[1, 0, 0, 0, 0],
    [0, 2, 0, 0, 0],
    [0, 0, 3, 0, 0],
    [0, 0, 0, 4, 0],
    [0, 0, 0, 0, 5]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=2)

Test 1 passed!
Test 2 passed!


### Problem 1.2

Write a function **my_eye** (without using torch.eye) that takes $n$ and returns the identity matrix of size $n$ with type *float torch.Tensor*. 

In [273]:
def my_eye(n):
  return torch.diag(torch.ones(n, dtype=torch.float))

In [274]:
# Test 1
output = my_eye(2)
correct = torch.tensor([[1, 0], [0, 1]], dtype=torch.float)
validate_solution(output, correct, test_num=1)

# Test 2
output = my_eye(5)
correct = torch.tensor(
    [[1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 0, 1, 0],
    [0, 0, 0, 0, 1]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=2)

Test 1 passed!
Test 2 passed!


## 2. Indexing, slicing and reshaping

### Indexing and slicing

In [275]:
# You can index and slice Pytorch tensors like Python lists and numpy arrays
x = torch.ones(4, 4)
print("First row:\n",x[0])
print("First column:\n", x[:, 0])
print("Last column:\n", x[..., -1])
x[:,1] = 0
print("x modified:\n", x)

First row:
 tensor([1., 1., 1., 1.])
First column:
 tensor([1., 1., 1., 1.])
Last column:
 tensor([1., 1., 1., 1.])
x modified:
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### Reshaping and transposing

In [276]:
# You can change the shape of tensors by reshape() function
x = torch.ones(4, 4)
y = torch.arange(1, 10)

z1 = x.reshape(2, 8)
z2 = x.reshape(16, 1)
z3 = x.reshape(1, -1)
z4 = x.flatten()  # flat your tensor

z5 = y.reshape(3, 3)
z6 = z5.T

print("z1:\n", z1)
print("z2:\n", z2)
print("z3:\n", z3)
print("z4:\n", z4)
print("z5:\n", z5)
print("z6:\n", z6)

z1:
 tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])
z2:
 tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])
z3:
 tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
z4:
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
z5:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
z6:
 tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


### Advanced indexing

In [277]:
# You can index your tensor by a list of indices
x = torch.arange(16).reshape(4, 4)

z1 = x[[1, 3], :]
z2 = x[:, [0, 2]]
z3 = x[[1, 3], [0, 2]]
z4 = x[::2, :]
z5 = x[1:3, :2]
z6 = x[1:3, [1, 3]]
z7 = x.flip(0)  # revert your tensor along 1st dimension
z8 = x.flip(1)  # revert your tensor along 2nd dimension

print("x:\n", x)
print("z1:\n", z1)
print("z2:\n", z2)
print("z3:\n", z3)
print("z4:\n", z4)
print("z5:\n", z5)
print("z6:\n", z6)
print("z7:\n", z7)
print("z8:\n", z8)

x:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
z1:
 tensor([[ 4,  5,  6,  7],
        [12, 13, 14, 15]])
z2:
 tensor([[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14]])
z3:
 tensor([ 4, 14])
z4:
 tensor([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]])
z5:
 tensor([[4, 5],
        [8, 9]])
z6:
 tensor([[ 5,  7],
        [ 9, 11]])
z7:
 tensor([[12, 13, 14, 15],
        [ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]])
z8:
 tensor([[ 3,  2,  1,  0],
        [ 7,  6,  5,  4],
        [11, 10,  9,  8],
        [15, 14, 13, 12]])


### Copying tensors

In [278]:
# You should be cautious when you use the operator "=" because it makes a shallow copy
# If you want a deep copy you should use clone() function 
x = torch.ones((2, 3))

y = x
z = x.clone()

x[0] = 0

print("x:\n", x)
print("y:\n", y)
print("z:\n", z)

x:
 tensor([[0., 0., 0.],
        [1., 1., 1.]])
y:
 tensor([[0., 0., 0.],
        [1., 1., 1.]])
z:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])


### Problem 2.1

Write a function **zebra_matrix** that takes $m, n, dim$ and returns the matrix of size $m\times n$ with type *float torch.Tensor* that consists of ones and zeros. 

For $dim = 0$ the matrix should be like $\quad
\begin{pmatrix}
1 & 0 & 1 & \dots \\
1 & 0 & 1 & \dots \\
\vdots & \vdots & \ddots \\
1 & 0 & 1 & \dots
\end{pmatrix}
$. 

For $dim = 1$ the matrix should be like $\quad
\begin{pmatrix}
1 & 1 & \dots & 1 \\
0 & 0 & \dots & 0 \\
1 & 1 & \dots & 1\\
\vdots & \vdots & \ddots & \vdots
\end{pmatrix}
$. 

In [279]:
def zebra_matrix(m, n, dim):
    x = torch.ones((m, n))
    if dim == 0:
      x[..., 1::2] = 0
    elif dim == 1:
      x[1::2, ...] = 0
    return x

In [280]:
# Test 1
output = zebra_matrix(5, 4, 0)
correct = torch.tensor(
    [[1., 0., 1., 0.],
    [1., 0., 1., 0.],
    [1., 0., 1., 0.],
    [1., 0., 1., 0.],
    [1., 0., 1., 0.]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=1)

# Test 2
output = zebra_matrix(5, 4, 1)
correct = torch.tensor(
    [[1., 1., 1., 1.],
    [0., 0., 0., 0.],
    [1., 1., 1., 1.],
    [0., 0., 0., 0.],
    [1., 1., 1., 1.]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=2)

Test 1 passed!
Test 2 passed!


### Problem 2.2

Write a function **zero_diag** that takes a matrix $x$ and returns the matrix $y$ with zeros in the diagonal and the same elements as in $x$ off the diagonal.



In [281]:
def zero_diag(x):
  dim1 = x.shape[0]
  dim2 = x.shape[1]
  x = x.flatten()
  x[torch.arange(0, dim1 * dim2, dim1 + 1)] = 0
  x = x.reshape(dim1, dim2)

  return x

In [282]:
# Test 1
output = zero_diag(torch.ones(2, 2))
correct = torch.tensor(
    [[0., 1.],
    [1., 0.]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=1)

# Test 2
output = zero_diag(torch.ones(5, 5))
correct = torch.tensor(
    [[0., 1., 1., 1., 1.],
    [1., 0., 1., 1., 1.],
    [1., 1., 0., 1., 1.],
    [1., 1., 1., 0., 1.],
    [1., 1., 1., 1., 0.]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=2)

Test 1 passed!
Test 2 passed!


### Problem 2.3

Write a function **zero_off_diag** that takes a matrix $x$ and returns the matrix $y$ with zeros off the diagonal and the same elements as in $x$ in the diagonal.

In [283]:
def zero_off_diag(x):
  dim1 = x.shape[0]
  dim2 = x.shape[1]
  x = x.flatten()
  diag = x[torch.arange(0, dim1 * dim2, dim1 + 1)]
  return torch.diag(diag)

  return x

In [284]:
# Test 1
output = zero_off_diag(torch.ones(2, 2))
correct = torch.tensor(
    [[1., 0.],
    [0., 1.]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=1)

# Test 2
output = zero_off_diag(torch.ones(5, 5))
correct = torch.tensor(
    [[1., 0., 0., 0., 0.],
    [0., 1., 0., 0., 0.],
    [0., 0., 1., 0., 0.],
    [0., 0., 0., 1., 0.],
    [0., 0., 0., 0., 1.]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=2)

Test 1 passed!
Test 2 passed!


### Problem 2.4

Write a function **descending_numbers** that takes $m, n$ and returns the matrix of size $m\times n$ $\quad$ 
\begin{pmatrix} 
m \cdot n & m \cdot n - 1 & \dots & m \cdot n - n + 1 \\
(m - 1) \cdot n & (m - 1) \cdot n - 1 & \dots & (m - 1) \cdot n - n + 1 \\
\vdots & \vdots & \ddots & \vdots \\
n & n - 1 & \dots & 1
\end{pmatrix} with type *float torch.Tensor*.



In [285]:
def descending_numbers(m, n):
  return torch.arange(1, m*n + 1, dtype=torch.float).reshape(m, n).flip(1).flip(0)
    

In [286]:
# Test 1
output = descending_numbers(2, 3)
correct = torch.tensor(
    [[6, 5, 4],
    [3, 2, 1]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=1)

# Test 2
output = descending_numbers(5, 4)
correct = torch.tensor(
    [[20, 19, 18, 17],
    [16, 15, 14, 13],
    [12, 11, 10,  9],
    [ 8,  7,  6,  5],
    [ 4,  3,  2,  1]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=2)

Test 1 passed!
Test 2 passed!


### Problem 2.5

Write a function **anti_diag_matrix** that takes a vector $x = (x_1, \dots, x_n)$ and returns the anti-diagonal matrix $\quad
\begin{pmatrix}
0 & \dots & 0 & x_1 \\
0 & \dots & x_2 & 0 \\
\vdots & \vdots & \ddots & \vdots \\
x_n & 0 & \dots & n
\end{pmatrix}
$ with type *float torch.Tensor*. 

In [287]:
def anti_diag_matrix(x):
    return torch.diag(x.flip(0)).flip(0)

In [288]:
# Test 1
output = anti_diag_matrix(torch.tensor([1, 2], dtype=torch.float))
correct = torch.tensor(
    [[0., 1.],
    [2., 0.]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=1)

# Test 2
output = anti_diag_matrix(torch.tensor([1, 2, 3, 4, 5], dtype=torch.float))
correct = torch.tensor(
    [[0., 0., 0., 0., 1.],
    [0., 0., 0., 2., 0.],
    [0., 0., 3., 0., 0.],
    [0., 4., 0., 0., 0.],
    [5., 0., 0., 0., 0.]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=2)

Test 1 passed!
Test 2 passed!


### Joining tensors

In [289]:
# You can concatenate (using torch.cat) and stack tensors to creating new tensors
x = torch.ones((2, 3))
y = torch.zeros((2, 3))

z1 = torch.cat([x, y], dim=0)
z2 = torch.cat([x, y], dim=1)
z3 = torch.cat([x[0], y[0]], dim=0)
z4 = torch.stack([x[0], y[0]])

print("x:\n", x)
print("y:\n", y)
print("z1:\n", z1)
print("z2:\n", z2)
print("z3:\n", z3)
print("z4:\n", z4)

x:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
y:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
z1:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])
z2:
 tensor([[1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.]])
z3:
 tensor([1., 1., 1., 0., 0., 0.])
z4:
 tensor([[1., 1., 1.],
        [0., 0., 0.]])


### Problem 2.6 (you can use one for/while loop)

Write a function **arange_matrix** that takes $m, n$ and returns the matrix of size $m\times n$ $\quad
\begin{pmatrix}
1 & 2 & \dots & n \\
1 & 2 & \dots & n \\
\vdots & \vdots & \ddots & \vdots \\
1 & 2 & \dots & n
\end{pmatrix}
$ with type *float torch.Tensor*. 

In [290]:
def arange_matrix(m, n):
  x = torch.ones((m, 1))
  for i in range(2, n + 1):
    x = torch.cat([x, torch.ones((m, 1)) * i], dim = 1)
  return x
  

In [291]:
# Test 1
output = arange_matrix(2, 3)
correct = torch.tensor(
    [[1, 2, 3],
    [1, 2, 3]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=1)

# Test 2
output = arange_matrix(5, 4)
correct = torch.tensor(
    [[1, 2, 3, 4],
    [1, 2, 3, 4],
    [1, 2, 3, 4],
    [1, 2, 3, 4],
    [1, 2, 3, 4]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=2)

Test 1 passed!
Test 2 passed!


## 3. Operations on Tensors

### Matrix addition

In [292]:
# You can add matrices using three different ways!
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float)
y = torch.tensor([[4, 5, 6], [1, 2, 3]], dtype=torch.float)

z1 = x + y
z2 = x.add(y)
z3 = torch.rand_like(z2)
torch.add(x, y, out=z3)

print("z1:\n", z1)
print("z2:\n", z2)
print("z3:\n", z3)

z1:
 tensor([[5., 7., 9.],
        [5., 7., 9.]])
z2:
 tensor([[5., 7., 9.],
        [5., 7., 9.]])
z3:
 tensor([[5., 7., 9.],
        [5., 7., 9.]])


### Matrix multiplication

In [293]:
# You can multiplicate matrices using three different ways!
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float)
y = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float)

z1 = x @ y
z2 = x.matmul(y)
z3 = torch.rand_like(z2)
torch.matmul(x, y, out=z3)

print("z1:\n", z1)
print("z2:\n", z2)
print("z3:\n", z3)

z1:
 tensor([[22., 28.],
        [49., 64.]])
z2:
 tensor([[22., 28.],
        [49., 64.]])
z3:
 tensor([[22., 28.],
        [49., 64.]])


### Element-wise operations

In [294]:
# You can do many different element-wise operations
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float)
y = torch.tensor([[4, 5, 6], [1, 2, 3]], dtype=torch.float)

z1 = x + 1
z2 = x * 2
z3 = x / 2
z4 = x ** 2
z5 = x * y
z6 = x + torch.tensor([1, 2, 3])
z7 = x + torch.tensor([[1], [2]])

z8 = torch.exp(x)
z9 = torch.log(x)
z10 = torch.sqrt(x)

z11 = x.exp()
z12 = x.log()
z13 = x.sqrt()

print("z1:\n", z1)
print("z2:\n", z2)
print("z3:\n", z3)
print("z4:\n", z4)
print("z5:\n", z5)
print("z6:\n", z6)
print("z7:\n", z7)
print("z8:\n", z8)
print("z9:\n", z9)
print("z10:\n", z10)
print("z11:\n", z11)
print("z12:\n", z12)
print("z13:\n", z13)


z1:
 tensor([[2., 3., 4.],
        [5., 6., 7.]])
z2:
 tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
z3:
 tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])
z4:
 tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
z5:
 tensor([[ 4., 10., 18.],
        [ 4., 10., 18.]])
z6:
 tensor([[2., 4., 6.],
        [5., 7., 9.]])
z7:
 tensor([[2., 3., 4.],
        [6., 7., 8.]])
z8:
 tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])
z9:
 tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])
z10:
 tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])
z11:
 tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])
z12:
 tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])
z13:
 tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])


### Problem 3.1

Write a function **gram_matrix** that takes a matrix $A = (a_1| \dots | a_n)$ and returns the matrix of size $n\times n$ $\quad
\begin{pmatrix}
a_1^Ta_1 & a_1^Ta_2 & \dots & a_1^Ta_n \\
a_2^Ta_1 & a_2^Ta_2 & \dots & a_2^Ta_n \\
\vdots & \vdots & \ddots & \vdots \\
a_n^Ta_1 & a_n^Ta_2 & \dots & a_n^Ta_n
\end{pmatrix}
$ with type *float torch.Tensor*. 

In [295]:
def gram_matrix(A):
    return A.T.matmul(A)

In [296]:
# Test 1
output = gram_matrix(torch.tensor([[1, 2], [1, 2]], dtype=torch.float))
correct = torch.tensor(
    [[2., 4.],
    [4., 8.]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=1)

# Test 2
output = gram_matrix(torch.tensor([[1, 2, 3], [1, 2, 3]], dtype=torch.float))
correct = torch.tensor(
    [[ 2.,  4.,  6.],
    [ 4.,  8., 12.],
    [ 6., 12., 18.]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=2)

Test 1 passed!
Test 2 passed!


### Problem 3.2

Write a function **increment_diag_decrement_off_diag** that takes a matrix $A = \begin{pmatrix}
a_{11} & a_{11} & \dots & a_{1n} \\
a_{21} & a_{22} & \dots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{n2} & \dots & a_{mn}
\end{pmatrix}$ and returns the matrix $\quad
\begin{pmatrix}
a_{11} + 1 & a_{11} - 1 & \dots & a_{1n} - 1 \\
a_{21} - 1 & a_{22} + 1 & \dots & a_{2n} - 1 \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} - 1 & a_{n2} - 1 & \dots & a_{mn} + 1
\end{pmatrix}
$ with type *float torch.Tensor*. 

In [297]:
def increment_diag_decrement_off_diag(A):
  A -=1
  A[torch.arange(A.shape[0]), torch.arange(A.shape[1])] +=2
  return A

In [298]:
# Test 1
output = increment_diag_decrement_off_diag(torch.ones(2, 2))
correct = torch.tensor(
    [[2., 0.],
    [0., 2.]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=1)

# Test 2
output = increment_diag_decrement_off_diag(
    torch.tensor([[1, 2, 3], [1, 2, 3], [1, 2, 3]], dtype=torch.float)
)
correct = torch.tensor(
    [[2., 1., 2.],
    [0., 3., 2.],
    [0., 1., 4.]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=2)

Test 1 passed!
Test 2 passed!


### Problem 3.3

Write a function **exp_diag_log_off_diag** that takes a matrix $A = \begin{pmatrix}
a_{11} & a_{11} & \dots & a_{1n} \\
a_{21} & a_{22} & \dots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{n2} & \dots & a_{mn}
\end{pmatrix}$ and returns the matrix $\quad
\begin{pmatrix}
\exp a_{11} & \log a_{11} & \dots & \log a_{1n} \\
\log a_{21} & \exp a_{22} & \dots & \log a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
\log a_{m1} & \log a_{n2} & \dots & \exp a_{mn}
\end{pmatrix}
$ with type *float torch.Tensor*. 

In [299]:
def exp_diag_log_off_diag(A):
    A = torch.log(A)
    A[torch.arange(A.shape[0]), torch.arange(A.shape[1])] = torch.exp(A[torch.arange(A.shape[0]), torch.arange(A.shape[1])])
    A[torch.arange(A.shape[0]), torch.arange(A.shape[1])] = torch.exp(A[torch.arange(A.shape[0]), torch.arange(A.shape[1])])
    return A

In [300]:
# Test 1
output = exp_diag_log_off_diag(torch.ones(2, 2))
correct = torch.tensor(
    [[2.7183, 0.0000],
    [0.0000, 2.7183]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=1)

# Test 2
output = exp_diag_log_off_diag(
    torch.tensor([[1, 2, 3], [1, 2, 3], [1, 2, 3]], dtype=torch.float)
)
correct = torch.tensor(
    [[ 2.7183,  0.6931,  1.0986],
    [ 0.0000,  7.3891,  1.0986],
    [ 0.0000,  0.6931, 20.0855]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=2)

Test 1 passed!
Test 2 passed!


### Problem 3.4 (you can use one for/while loop)

Write the function **exp_matrix** that takes a matrix $A$ and a number $n$ and returns the matrix $B = \sum\limits_{i=0}^n \dfrac{A^i}{i!}$. 

In [301]:
def exp_matrix(A, n):
  B = torch.eye(A.shape[0])
  result = 0
  for i in range(0, n + 1):
    result += B / np.math.factorial(i)
    B = A.matmul(B)
  return result


In [302]:
# Test 1
output = exp_matrix(torch.diag(torch.tensor([1, 2], dtype=torch.float)), 5)
correct = torch.tensor(
    [[2.7167, 0.0000],
    [0.0000, 7.2667]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=1)

# Test 2
output = exp_matrix(torch.ones(2, 2), 5)
correct = torch.tensor(
    [[4.1333, 3.1333],
    [3.1333, 4.1333]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=2)

# Test 3
output = exp_matrix(
    torch.tensor([[1, 2, 3], [1, 2, 3], [1, 2, 3]], dtype=torch.float), 5
)
correct = torch.tensor(
    [[30.8000, 59.6000, 89.4000],
    [29.8000, 60.6000, 89.4000],
    [29.8000, 59.6000, 90.4000]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=3)

Test 1 passed!
Test 2 passed!
Test 3 passed!


### Problem 3.5 (you can use two for/while loops but not nested!)

Write the function **binom_matrix** that takes two matrices $A, B$ and a number $n$ and calculates the matrix $C = (A + B)^n$ using the formula $(A + B)^n = \sum\limits_{i=0}^n C^i_nA^iB^{n - i}$ assuming that $AB = BA$. 

In [436]:
def binom_matrix(A, B, n):
  a_matrix = torch.eye(A.shape[1])
  b_matrix = torch.eye(B.shape[0])
  a_degrees = torch.tensor(a_matrix)
  b_degrees = torch.tensor(b_matrix)
  for i in range(1, n + 1):
    a_matrix = A.matmul(a_matrix)
    b_matrix = B.matmul(b_matrix)
    a_degrees = torch.cat([a_degrees, torch.tensor(a_matrix)], dim = 0)
    b_degrees = torch.cat([torch.tensor(b_matrix), b_degrees], dim = 0)

  result = 0
  for i in range(0, (n + 1)*A.shape[0], A.shape[0]):
      result += a_degrees[i : A.shape[0] + i , ...].matmul(b_degrees[i:A.shape[0] + i,...]) * np.math.factorial(n) / np.math.factorial(i / A.shape[0]) / np.math.factorial(n - i / A.shape[0]) 
  
  return result

In [437]:
A = torch.ones(3, 3)
B = torch.diag(torch.tensor([3, 3, 3], dtype=torch.float))
output = binom_matrix(A, B, 5)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: UserWarning: To copy construct from a tensor, it is recommended to use sourceTen

In [438]:
# Test 1
A = torch.diag(torch.tensor([2, 2], dtype=torch.float))
B = torch.tensor([[1, 2], [2, 1]], dtype=torch.float)
output = binom_matrix(A, B, 2)
correct = torch.tensor(
    [[13., 12.],
    [12., 13.]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=1)

# Test 2
A = torch.ones(3, 3)
B = torch.diag(torch.tensor([3, 3, 3], dtype=torch.float))
output = binom_matrix(A, B, 5)
correct = torch.tensor(
    [[2754., 2511., 2511.],
    [2511., 2754., 2511.],
    [2511., 2511., 2754.]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=2)

Test 1 passed!
Test 2 passed!


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: UserWarning: To copy construct from a tensor, it is recommended to use sourceTen

### Problem 3.6 (you can use one for/while loop)

Write a function **vandermonde_matrix** that takes a vector $x = (x_1, \dots, x_n)$ and returns the Vandermonde matrix $\quad
\begin{pmatrix}
1 & x_1 & x_1^2 & \dots & x_1^{n-1} \\
1 & x_2 & x_2^2 & \dots & x_2^{n-1} \\
\vdots & \vdots & \ddots & \vdots \\
1 & x_n & x_n^2 & \dots & x_n^{n-1}
\end{pmatrix}
$ with type *float torch.Tensor*. 

In [247]:
def vandermonde_matrix(x):
    van = torch.ones((x.shape[0], 1))
    x = x.reshape((x.shape[0], 1))
    for i in range(1, x.shape[0]):
      van = torch.cat([van, x**i], dim = 1)
    return van

In [250]:
# Test 1
output = vandermonde_matrix(torch.tensor([1, 2], dtype=torch.float))
correct = torch.tensor(
    [[1., 1.],
    [1., 2.]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=1)

# Test 2
output = vandermonde_matrix(torch.tensor([1, 2, 3], dtype=torch.float))
correct = torch.tensor(
    [[1., 1., 1.],
    [1., 2., 4.],
    [1., 3., 9.]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=2)

Test 1 passed!
Test 2 passed!


## 4. Advanced Operations on Tensors

### Aggregating operations

In [305]:
# You can compute different operations (sum, min, max, etc.) along some axes or along all matrix.
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float)

z1 = x.sum()
z2 = x.sum(dim=0)
z3 = x.sum(dim=1)

z4 = x.min()
z5 = x.min(dim=0)
z6 = x.min(dim=1)

print("z1:\n", z1)
print("z2:\n", z2)
print("z3:\n", z3)
print("z4:\n", z4)
print("z5:\n", z5)
print("z6:\n", z6)

z1:
 tensor(21.)
z2:
 tensor([5., 7., 9.])
z3:
 tensor([ 6., 15.])
z4:
 tensor(1.)
z5:
 torch.return_types.min(
values=tensor([1., 2., 3.]),
indices=tensor([0, 0, 0]))
z6:
 torch.return_types.min(
values=tensor([1., 4.]),
indices=tensor([0, 0]))


### Problem 4.1

Write a function **frobenius_norm** that takes a matrix $A$ and return the Frobenius norm of this matrix using the formula $\|A\|_F = \sqrt{\sum\limits_{ij} a_{ij}^2}$. 

In [306]:
def frobenius_norm(A):
    return torch.sqrt((A**2).sum())

In [307]:
# Test 1
output = frobenius_norm(torch.ones(2, 2))
correct = torch.tensor(2, dtype=torch.float)
validate_solution(output, correct, test_num=1)

# Test 2
output = frobenius_norm(torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float))
correct = torch.tensor(9.5394,  dtype=torch.float)
validate_solution(output, correct, test_num=2)

Test 1 passed!
Test 2 passed!


### Problem 4.2

Write a function **l1_norm** that takes a matrix $A$ and return the L1 norm of this matrix using the formula $\|A\|_1 = \max\limits_i\sum\limits_{j} |a_{ij}|$. 

In [308]:
def l1_norm(A):
    return A.abs().sum(dim = 1).max()

In [309]:
# Test 1
output = l1_norm(torch.ones(2, 2))
correct = torch.tensor(2, dtype=torch.float)
validate_solution(output, correct, test_num=1)

# Test 2
output = l1_norm(torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float))
correct = torch.tensor(15.,  dtype=torch.float)
validate_solution(output, correct, test_num=2)

Test 1 passed!
Test 2 passed!


### Problem 4.3

Write a function **l_inf_norm** that takes a matrix $A$ and return the L-infinum norm of this matrix using the formula $\|A\|_{\infty} = \max\limits_j\sum\limits_{i} |a_{ij}|$. 

In [310]:
def l_inf_norm(A):
    return A.abs().sum(dim = 0).max()

In [311]:
# Test 1
output = l_inf_norm(torch.ones(2, 2))
correct = torch.tensor(2, dtype=torch.float)
validate_solution(output, correct, test_num=1)

# Test 2
output = l_inf_norm(torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float))
correct = torch.tensor(9.,  dtype=torch.float)
validate_solution(output, correct, test_num=2)

Test 1 passed!
Test 2 passed!


### Problem 4.4 ((you can use two for/while loops but not nested!)

Write a function **saddle_point** that takes a matrix $A$ and returns the list of pairs $[(i_1, j_1), \dots, (i_n, j_n)]$ such that for each pair $(i_k, j_k)$ the corresponding element $a_{i_kj_k}$ of the matrix $A$ satifies two conditions $a_{i_kj_k} = \min\limits_j a_{i_kj}$ and $a_{i_kj_k} = \max\limits_i a_{ij_k}$. 

In [367]:
def saddle_point(A):
  res = torch.LongTensor()
  max_cols = A.max(dim=0).indices
  min_rows = A.min(dim = 1).indices
  for i in range(len(min_rows)):
    if(i == max_cols[min_rows[i]]):
      res = torch.cat([res, torch.tensor([[i, min_rows[i]]], dtype=torch.long)])
  return res


In [369]:
# Test 1
output = saddle_point(torch.tensor([[1, 1], [3, 2]], dtype=torch.float))
correct = torch.tensor([[1, 1]])
validate_solution(output, correct, test_num=1)

# Test 2
output = saddle_point(torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float))
correct = torch.tensor([[1, 0]])
validate_solution(output, correct, test_num=2)

Test 1 passed!
Test 2 passed!


### Problem 4.5

Write a function **normalize_columns** that takes a matrix $A = (a_1|\dots|a_n)$ and return the matrix $B = (\bar{a}_1|\dots|\bar{a}_n)$ where $\bar{a}_i = \dfrac{a_i}{\|a_i\|_2}$. 

In [380]:
def normalize_columns(A):
  x = A.clone()
  return A / torch.sqrt((x ** 2).sum(dim = 0))

In [381]:
# Test 1
output = normalize_columns(torch.tensor([[1, 1], [2, 2]], dtype=torch.float))
correct = torch.tensor(
    [[0.4472, 0.4472],
    [0.8944, 0.8944]], 
    dtype=torch.float
)
validate_solution(output, correct, test_num=1)

# Test 2
output = normalize_columns(torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float))
correct = torch.tensor(
    [[0.2425, 0.3714, 0.4472],
    [0.9701, 0.9285, 0.8944]],  
    dtype=torch.float
)
validate_solution(output, correct, test_num=2)

Test 1 passed!
Test 2 passed!


### Matrix operations

In [ ]:
# You can compute different characteristics of matrices
x = torch.tensor([[1, 2, 3], [0, 5, 6], [0, 0, 9]], dtype=torch.float)

print("trace:\n", x.trace())
print("det:\n", x.det())
print("inverse:\n", torch.inverse(x))

### Problem 4.6

Write a function **frobenius_norm2** that takes a matrix $A$ and returns the Frobenius norm using the formula $\|A\|_F = \sqrt{\text{tr}(A^TA)}$. 

In [382]:
def frobenius_norm2(A):
    return torch.sqrt((A.T.matmul(A)).trace())

In [383]:
# Test 1
output = frobenius_norm2(torch.ones(2, 2))
correct = torch.tensor(2, dtype=torch.float)
validate_solution(output, correct, test_num=1)

# Test 2
output = frobenius_norm2(
    torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float)
)
correct = torch.tensor(9.5394,  dtype=torch.float)
validate_solution(output, correct, test_num=2)

Test 1 passed!
Test 2 passed!


### Problem 4.7

Write a function **l2_distance** that takes two matrices $A, B$ and returns the L2 distance between them using the formula $\|A - B\|_F = \sqrt{\text{tr}((A - B)^T(A - B))}$. 

In [384]:
def l2_distance(A, B):
    return torch.sqrt(((A - B).T.matmul(A - B)).trace())

In [385]:
# Test 1
A = torch.ones(2, 2)
B = torch.tensor([[1, 2], [3, 4]], dtype=torch.float)
output = l2_distance(A, B)
correct = torch.tensor(3.7417, dtype=torch.float)
validate_solution(output, correct, test_num=1)

# Test 2
A = torch.ones(2, 3)
B = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float)
output = l2_distance(A, B)
correct = torch.tensor(7.4162,  dtype=torch.float)
validate_solution(output, correct, test_num=2)

Test 1 passed!
Test 2 passed!


### Problem 4.8

Write a function **charac_polynomial** that takes a matrix $A$ and a number $x$ and returns the value of the characteristic polynomial of the matrix $A$ at point $x$, i.e. the value of the function $\det(A - xE)$. 



In [386]:
def charac_polynomial(A, x):
    return (A - x * torch.eye(A.shape[0])).det()

In [387]:
# Test 1
output = charac_polynomial(torch.ones(2, 2), 1)
correct = torch.tensor(-1., dtype=torch.float)
validate_solution(output, correct, test_num=1)

# Test 2
output = charac_polynomial(torch.ones(5, 5), 2)
correct = torch.tensor(48.,  dtype=torch.float)
validate_solution(output, correct, test_num=2)

Test 1 passed!
Test 2 passed!


### Problem 4.9 (you can use one for/while loop)

Write a function **vandermonde_det** that takes a vector $x = (x_1, \dots, x_n)$ and returns the determinant of the Vandermonde matrix \begin{pmatrix}
1 & x_1 & x_1^2 & \dots & x_1^{n-1} \\
1 & x_2 & x_2^2 & \dots & x_2^{n-1} \\
\vdots & \vdots & \ddots & \vdots \\
1 & x_n & x_n^2 & \dots & x_n^{n-1}
\end{pmatrix}. 

In [388]:
def vandermonde_det(x):
    return vandermonde_matrix(x).det()

In [389]:
# Test 1
output = vandermonde_det(torch.tensor([1, 2], dtype=torch.float))
correct = torch.tensor(1., dtype=torch.float)
validate_solution(output, correct, test_num=1)

# Test 2
output = vandermonde_det(torch.tensor([1, 2, 3], dtype=torch.float))
correct = torch.tensor(2., dtype=torch.float)
validate_solution(output, correct, test_num=2)

Test 1 passed!
Test 2 passed!


### Problem 4.10

Write a function **generalized_inverse** that takes a matrix $A$ and returns its generalized inverse by the formula $(A^TA)^{-1}A^T$. 

In [392]:
def generalized_inverse(A):
    return torch.inverse((A.T.matmul(A))).matmul(A.T)

In [393]:
# Test 1
output = generalized_inverse(torch.tensor([[1], [2]], dtype=torch.float))
correct = torch.tensor([[0.2000, 0.4000]], dtype=torch.float)
validate_solution(output, correct, test_num=1)

# Test 2
output = generalized_inverse(torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float))
correct = torch.tensor(
    [[-1.3333, -0.3333,  0.6667],
    [ 1.0833,  0.3333, -0.4167]],
    dtype=torch.float
)
validate_solution(output, correct, test_num=2)

Test 1 passed!
Test 2 passed!
